version: 2.1
jobs:
  build-app:
    docker:
      - image: circleci/openjdk:11.0.6-jdk-buster

    working_directory: ~/reactive-learning

    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./mvnw clean install
      - run: mvn clean compile jib:build -Dimage=sreeraj1237/spring-reactive-learnings:$CIRCLE_BUILD_NUM

workflows:
  build-workflow:
    jobs:
      - build-app
